"""Export compiler intermediate code for the dashboard agent.

For every case in scripts/ir_cases.json this runs the TileBench analysis
skill's generators (triton_ir.py, tl_codegen.py, cutile_ir.py) against a
TileBench checkout and writes the text under data/ir/<platform>/<op>/, plus
data/ir/manifest.json. The generators compile for the named hardware and need
no GPU; nothing is launched.

    python scripts/export_ir.py --checkout <tilebench checkout at the profiled revision> \
        --generators <.../skills/tilebench-analysis/scripts> [--only relu] [--python <interpreter>]

Use the interpreter that has the pinned Triton, TileLang and cuda-tile
versions the profiles were captured with: a different version gives different
intermediate code.
"""

import argparse
import concurrent.futures
import gzip
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
KINDS = {
    "ttir": "Triton IR before the GPU passes",
    "ttgir": "Triton IR after the GPU passes (layouts, shared memory, tensor path, pipelining)",
    "ptx": "PTX: emitted by Triton, or produced by nvcc from TileLang's generated CUDA",
    "amdgcn": "AMD GCN assembly emitted by Triton",
    "cu": "CUDA source generated by TileLang",
    "tir": "TileLang TIR before its passes",
    "lowered.tir": "TileLang device TIR after its passes",
    "tileir": "cuTile front-end Tile IR (the back end after this is closed)",
}


def run(command, env):
    result = subprocess.run(command, capture_output=True, text=True, env=env)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip().splitlines()[-1] if result.stderr.strip() else "generator failed")
    start = result.stdout.find("{")
    return json.loads(result.stdout[start:]) if start >= 0 else {}


def generate(case, checkout, generators, python, tmp, env):
    impl = checkout / "tilebench" / "benchmarks" / "operators" / case["op"] / f"impl_{case['backend']}.py"
    kernel = case["kernel"]
    if case["backend"] == "triton":
        out = tmp / "triton"
        command = [python, str(generators / "triton_ir.py"), str(impl), kernel, "--hardware", case["platform"],
                   "--num-warps", str(case["num_warps"]), "--out", str(out)]
        if "num_stages" in case:
            command += ["--num-stages", str(case["num_stages"])]
        for arg in case["args"]:
            command += ["--arg", arg]
        info = run(command, env)
        kinds = ("ttir", "ttgir", "amdgcn" if (out / f"{kernel}.amdgcn").exists() else "ptx")
        return {kind: out / f"{kernel}.{kind}" for kind in kinds}, {"triton": info.get("triton")}, command
    if case["backend"] == "tilelang":
        files = {"cu": tmp / "tl.cu", "tir": tmp / "tl.tir", "lowered.tir": tmp / "tl.lowered.tir", "ptx": tmp / "tl.ptx"}
        command = [python, str(generators / "tl_codegen.py"), str(impl), kernel, "--hardware", case["platform"],
                   "--out", str(files["cu"]), "--tir", str(files["tir"]), "--lowered-tir", str(files["lowered.tir"]),
                   "--ptx", str(files["ptx"])]
        for tensor in case["tensors"]:
            command += ["--tensor", tensor]
        for item in case["kw"]:
            command += ["--kw", item]
        info = run(command, env)
        nvcc = subprocess.run(["nvcc", "--version"], capture_output=True, text=True, env=env).stdout
        release = re.search(r"release ([\d.]+)", nvcc)
        return files, {"tilelang": info.get("tilelang"), "nvcc": release.group(1) if release else None}, command
    files = {"tileir": tmp / "ct.tileir"}
    command = [python, str(generators / "cutile_ir.py"), str(impl), kernel, "--hardware", case["platform"],
               "--out", str(files["tileir"])]
    for arg in case["args"]:
        command += ["--arg", arg]
    info = run(command, env)
    return files, {"cuda_tile": info.get("cuda_tile"), "symbol": info.get("symbol")}, command


def profile_kernels(platform, op, backend, dtype):
    manifest = ROOT / "data" / "profiles_json" / "manifest.json"
    if not manifest.exists():
        return None
    for report in json.loads(manifest.read_text())["reports"]:
        if (report["platform"], report["op"], report["backend"], report["dtype"]) == (platform, op, backend, dtype):
            data = json.loads(gzip.decompress((manifest.parent / report["file"]).read_bytes()))
            out = []
            for kernel in data["kernels"]:
                threads = 1 if kernel.get("block_size") else None
                workgroup = (kernel.get("metrics") or {}).get("Wavefront / Wavefront Launch Stats / Workgroup Size [Avg]")
                if threads is None and workgroup:
                    threads = int(workgroup[0])
                for part in re.findall(r"\d+", kernel.get("block_size") or ""):
                    threads *= int(part)
                out.append((kernel["name"], threads, kernel.get("launches") or 1))
            return out
    return None


def check_against_profile(case, files, versions):
    """Compare what was generated with the kernel the saved profile recorded."""
    kernels = profile_kernels(case["platform"], case["op"], case["backend"], case["dtype"])
    if kernels is None:
        return None, "no exported profile to check against"
    merged = len(kernels) == 1 and kernels[0][2] > 1 and case.get("sibling_kernels", 1) > 1
    kernels = [(name, threads) for name, threads, _ in kernels]
    names = [name for name, _ in kernels]
    if case["backend"] == "cutile":
        symbol = versions.get("symbol")
        if symbol in names:
            return True, "generated kernel symbol equals the profiled kernel name (it encodes the argument signature and constants)"
        return False, f"generated kernel symbol {symbol} is not among the profiled kernels {names[:3]}"
    if case["backend"] == "triton":
        threads = (64 if case["platform"] == "MI300X" else 32) * case["num_warps"]
        if any(name == case["kernel"] and count == threads for name, count in kernels):
            return True, f"kernel name and thread count ({threads}) equal the profiled launch"
        if any(name == case["kernel"] and count is None for name, count in kernels):
            return True, "kernel name equals the profiled kernel (this profile does not record the thread count); shape and configuration are the ones stored with the profile"
        return False, f"no profiled kernel named {case['kernel']} with {threads} threads; profile has {kernels[:3]}"
    bounds = re.search(r"__launch_bounds__\((\d+)", files["cu"].read_text())
    threads = int(bounds.group(1)) if bounds else None
    if any(count == threads for _, count in kernels):
        return True, f"thread count ({threads}) equals a profiled kernel's launch"
    if merged:
        return None, (f"generated code launches {threads} threads; the profile lists this operator's {case['sibling_kernels']} "
                      f"kernels under one name with one launch size ({kernels[0][1]}), so this kernel cannot be checked against it")
    return False, f"generated code launches {threads} threads; profile has {kernels[:3]}"


def export(case, args, env, revision):
    variant = case.get("variant", 1)
    key = (case["platform"], case["op"], case["backend"], case["dtype"], case["kernel"], variant)
    stem = case["kernel"] if variant == 1 else f"{case['kernel']}.v{variant}"
    with tempfile.TemporaryDirectory() as scratch:
        local = dict(env, TRITON_CACHE_DIR=str(Path(scratch) / "triton_cache"))
        files, versions, _ = generate(case, args.checkout, args.generators, args.python, Path(scratch), local)
        ok, check = check_against_profile(case, files, versions)
        target = args.out / case["platform"] / case["op"]
        target.mkdir(parents=True, exist_ok=True)
        written = []
        for kind, source in files.items():
            text = source.read_text()
            name = f"{case['backend']}_{case['dtype']}.{stem}.{kind}"
            (target / name).write_text(text)
            written.append({"kind": kind, "what": KINDS[kind], "file": f"{case['platform']}/{case['op']}/{name}",
                            "lines": text.count("\n"), "chars": len(text),
                            "sha256": hashlib.sha256(text.encode()).hexdigest()[:16]})
    entry = {k: case[k] for k in ("platform", "op", "backend", "dtype", "kernel", "shape", "config") if k in case}
    entry["variant"] = variant
    entry.update({"files": written, "versions": versions, "source_revision": revision,
                  "profile_check": check, "profile_check_ok": ok})
    for extra in ("args", "tensors", "kw", "num_warps", "num_stages", "note", "verified", "config_note", "launch_variants"):
        if case.get(extra) is not None:
            entry[extra] = case[extra]
    return key, entry


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--checkout", type=Path, required=True)
    parser.add_argument("--generators", type=Path, required=True)
    parser.add_argument("--python", default=sys.executable)
    parser.add_argument("--cases", type=Path, default=ROOT / "scripts" / "ir_cases.json")
    parser.add_argument("--out", type=Path, default=ROOT / "data" / "ir")
    parser.add_argument("--only", action="append", default=[], help="operator to export; repeat")
    parser.add_argument("--revision", help="source revision of the checkout, when it is not a git work tree")
    parser.add_argument("--jobs", type=int, default=1)
    parser.add_argument("--platform", action="append", default=[],
                        help="platform to export; repeat. Use one checkout per platform when their sources differ")
    parser.add_argument("--backend", action="append", default=[], help="backend to export; repeat")
    args = parser.parse_args()
    env = dict(os.environ, TL_DISABLE_WARP_SPECIALIZED="1", PYTHONPATH=str(args.checkout))
    revision = args.revision or subprocess.run(["git", "-C", str(args.checkout), "rev-parse", "HEAD"],
                                               capture_output=True, text=True).stdout.strip() or None
    manifest_path = args.out / "manifest.json"
    previous = json.loads(manifest_path.read_text())["entries"] if manifest_path.exists() else []
    entries = {(e["platform"], e["op"], e["backend"], e["dtype"], e["kernel"], e.get("variant", 1)): e for e in previous}
    cases = [c for c in json.loads(args.cases.read_text())["cases"]
             if (not args.only or c["op"] in args.only) and (not args.backend or c["backend"] in args.backend)
             and (not args.platform or c["platform"] in args.platform)]
    siblings = {}
    for c in json.loads(args.cases.read_text())["cases"]:
        siblings.setdefault((c["platform"], c["op"], c["backend"], c["dtype"]), set()).add(c["kernel"])
    for c in cases:
        c["sibling_kernels"] = len(siblings[(c["platform"], c["op"], c["backend"], c["dtype"])])
    failures = []

    def save():
        args.out.mkdir(parents=True, exist_ok=True)
        manifest_path.write_text(json.dumps({"entries": [entries[k] for k in sorted(entries)]}, indent=1) + "\n")

    with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as pool:
        futures = {pool.submit(export, case, args, env, revision): case for case in cases}
        for done, future in enumerate(concurrent.futures.as_completed(futures), 1):
            case = futures[future]
            label = "/".join((case["platform"], case["op"], case["backend"], case["dtype"], case["kernel"])) + f"#{case.get('variant', 1)}"
            try:
                key, entry = future.result()
            except Exception as error:
                failures.append(label)
                entries.pop((case["platform"], case["op"], case["backend"], case["dtype"], case["kernel"], case.get("variant", 1)), None)
                print(f"FAILED {label}: {str(error)[:160]}", flush=True)
                continue
            entries[key] = entry
            flag = {True: "matches profile", False: "PROFILE MISMATCH", None: "unchecked"}[entry["profile_check_ok"]]
            print(f"ok {label}: {flag}", flush=True)
            if done % 20 == 0:
                save()
    save()
    print(f"{len(entries)} entries in {manifest_path}; {len(failures)} failed")
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
