"""Frozen case set of every formal task (protocol revision 4).

A formal task is (operator, selected dtype, device, DSL, model, condition).
Each generated candidate is evaluated on ALL configured cases of the
operator's selected dtype (`representative_dtypes.yaml`), in the operator's
config grid order; generation does not multiply by the number of cases.
Base and Enhanced use the identical case IDs.

`manifests/case_sets.yaml` is generated by `build_manifest()` from the
operator configs (tilebench.data.tensors.expand_cases, the framework's case
source) and validated on every load: an entry whose case IDs, parameters,
problem sizes or case-source hash differ from the configs is an error.
Nothing is synthesized: a case exists only if the config expands to it.

`domain()` is the generator-visible description of a case set: the constant
parameters with their values and, for every parameter that varies, its
integer range and common divisor. It never lists the individual cases."""
from __future__ import annotations

import hashlib
import math
from functools import reduce

from tilebench.data.tensors import expand_cases, infer_problem_size
from tilebench.paths import list_operators, operator_config

from tilebench.llm.v2.manifests import schema as ms
from tilebench.llm.v2.tasks.case_selection import case_params, load_operator_config, make_case_id

MANIFEST_NAME = "case_sets.yaml"
SCHEMA = "tilebench-llm-case-sets/1"
CASES_PER_TASK = 20
CASE_SOURCE_KEYS = ("test_cases", "case_grid", "case_defaults", "case_preset")


def case_source_sha256(config: dict) -> str:
    """Hash of the config sections that define the cases (not the benchmark/plot/metric sections)."""
    return ms.sha256_text(ms.canonical_json({k: config.get(k) for k in CASE_SOURCE_KEYS}))


def operator_cases(operator: str, dtype: str, config: dict | None = None) -> list[dict]:
    """Every expanded case of `dtype`, in grid order, with its case_id."""
    config = config if config is not None else load_operator_config(operator)
    out = []
    for idx, case in enumerate(expand_cases(operator, config)):
        if str(case.get("dtype", "fp32")) != dtype:
            continue
        params = case_params(case)
        out.append({"case_id": make_case_id(params, dtype), "case_index": idx, "params": params,
                    "problem_size": int(infer_problem_size(operator, params)), "dtype": dtype})
    return out


def case_set_id(operator: str, dtype: str, case_ids: list[str]) -> str:
    return "cs" + ms.sha256_text(ms.canonical_json({"operator": operator, "dtype": dtype, "case_ids": list(case_ids)}))[:14]


def build_manifest(operators: list[str] | None = None, selected: dict[str, str] | None = None) -> dict:
    from tilebench.llm.v2.tasks.representative import selected as rep_selected
    selected = selected if selected is not None else rep_selected()
    entries = {}
    for op in operators or list_operators():
        cfg = load_operator_config(op)
        dt = selected[op]
        cases = operator_cases(op, dt, cfg)
        entries[op] = {"dtype": dt, "case_set_id": case_set_id(op, dt, [c["case_id"] for c in cases]),
                       "n_cases": len(cases), "case_source_sha256": case_source_sha256(cfg),
                       "config_file_sha256": hashlib.sha256(operator_config(op).read_bytes()).hexdigest(),
                       "cases": cases}
    return {"schema": SCHEMA, "cases_per_task": CASES_PER_TASK,
            "rule": "every configured case of the operator's selected dtype, in config grid order (expand_cases); "
                    "no synthesized case; identical for every device, DSL, model and condition",
            "operators": entries}


_CACHE: dict[str, dict] = {}


def load_manifest() -> dict:
    """The validated frozen manifest (validated once per file content per process; callers must not mutate it)."""
    raw = (ms.MANIFEST_DIR / MANIFEST_NAME).read_bytes() if (ms.MANIFEST_DIR / MANIFEST_NAME).exists() else b""
    key = hashlib.sha256(raw).hexdigest()
    if key not in _CACHE:
        data = ms.load_yaml(MANIFEST_NAME)
        validate_manifest(data)
        _CACHE[key] = data
    return _CACHE[key]


def validate_manifest(data: dict, operators: list[str] | None = None) -> None:
    if data.get("schema") != SCHEMA:
        raise ms.ManifestError(f"{MANIFEST_NAME}: schema must be {SCHEMA}")
    if data.get("status") != "frozen" or not data.get("approved_by"):
        raise ms.ManifestError(f"{MANIFEST_NAME}: must be frozen with approved_by")
    if data.get("cases_per_task") != CASES_PER_TASK:
        raise ms.ManifestError(f"{MANIFEST_NAME}: cases_per_task must be {CASES_PER_TASK}")
    ops = operators or list_operators()
    entries = data.get("operators") or {}
    if sorted(entries) != sorted(ops):
        raise ms.ManifestError(f"{MANIFEST_NAME}: operators {sorted(set(ops) ^ set(entries))} missing or unknown")
    expected = build_manifest(ops)["operators"]
    for op in ops:
        got, exp = entries[op], expected[op]
        if got.get("dtype") != exp["dtype"]:
            raise ms.ManifestError(f"{MANIFEST_NAME}: {op} dtype {got.get('dtype')!r} != representative dtype {exp['dtype']!r}")
        if got.get("case_source_sha256") != exp["case_source_sha256"]:
            raise ms.ManifestError(f"{MANIFEST_NAME}: {op} case source changed (config.yaml case sections differ from the freeze)")
        strip = lambda cs: [{k: c[k] for k in ("case_id", "case_index", "params", "problem_size", "dtype")} for c in cs]  # noqa: E731
        if strip(got.get("cases") or []) != strip(exp["cases"]):
            raise ms.ManifestError(f"{MANIFEST_NAME}: {op} cases differ from the config expansion")
        if got.get("case_set_id") != exp["case_set_id"] or got.get("n_cases") != len(exp["cases"]):
            raise ms.ManifestError(f"{MANIFEST_NAME}: {op} case_set_id / n_cases inconsistent")
        if len(exp["cases"]) != CASES_PER_TASK:
            raise ms.ManifestError(f"{MANIFEST_NAME}: {op} has {len(exp['cases'])} cases, the protocol requires {CASES_PER_TASK}")


def case_set(operator: str, data: dict | None = None) -> dict:
    data = data if data is not None else load_manifest()
    try:
        return data["operators"][operator]
    except KeyError:
        raise ms.ManifestError(f"{MANIFEST_NAME}: no case set for {operator}") from None


def domain(cases: list[dict]) -> dict:
    """Generator-visible parameter domain: constants and per-parameter ranges (never the case list)."""
    keys = sorted({k for c in cases for k in c["params"]})
    const, varying = {}, {}
    for k in keys:
        vals = [c["params"].get(k) for c in cases]
        distinct = []
        for v in vals:
            if v not in distinct:
                distinct.append(v)
        if len(distinct) == 1:
            const[k] = distinct[0]
            continue
        ints = [v for v in distinct if isinstance(v, int) and not isinstance(v, bool)]
        if len(ints) == len(distinct):
            varying[k] = {"min": min(ints), "max": max(ints), "multiple_of": reduce(math.gcd, ints)}
        else:
            varying[k] = {"values_are": "non-integer; see the functional reference"}
    return {"constant": const, "varying": varying, "n_cases": len(cases)}
