"""Frozen kinds of the arguments every task passes to `run()` (checker v4).

The evaluator calls a candidate as `run(*inputs)`, `inputs` being the
operator's input generator output for a case (tilebench.data.tensors). Several
interfaces pass Python numbers next to the tensors (`run(input, N, C, H, W,
kernel_size, stride, padding)`), and not every such number is a case
parameter (`W` defaults to `H`). `manifests/input_kinds.yaml` records, per
operator and its selected dtype, the kind of every positional input --
`tensor`, `scalar` (a Python int/float/bool) or `other` -- derived by calling
the generator on every frozen case of the operator's case set (the kinds must
agree across the cases). It is validated against case_sets.yaml on load and
covered by the checker fingerprint. The compliance checker's cache data-flow
treats a positional `run()` parameter that receives a `scalar` input as
configuration, not as a tensor argument.

    python -m tilebench.llm.v2.tasks.input_kinds   # regenerates the manifest (needs the GPU)"""
from __future__ import annotations

from tilebench.llm.v2.manifests import schema as ms

MANIFEST_NAME = "input_kinds.yaml"
SCHEMA = "tilebench-llm-input-kinds/1"
KINDS = ("tensor", "scalar", "other")


def kind_of(value) -> str:
    import torch
    if isinstance(value, torch.Tensor):
        return "tensor"
    if isinstance(value, (bool, int, float)):
        return "scalar"
    return "other"


def derive(operator: str, entry: dict) -> list[str]:
    """Kinds of the generator's outputs, identical on every frozen case of the operator (else ValueError)."""
    import torch
    from tilebench.core.dtypes import resolve_dtype
    from tilebench.data.tensors import get_generator
    gen, dtype = get_generator(operator), resolve_dtype(entry["dtype"])
    kinds = None
    for case in entry["cases"]:
        inp = gen(**case["params"], dtype=dtype)
        inp = inp if isinstance(inp, tuple) else (inp,)
        k = [kind_of(v) for v in inp]
        del inp
        if kinds is None:
            kinds = k
        elif k != kinds:
            raise ValueError(f"{operator}: input kinds differ between cases ({kinds} vs {k} at {case['case_id']})")
    torch.cuda.empty_cache()
    return kinds or []


def build_manifest(case_sets: dict | None = None) -> dict:
    case_sets = case_sets if case_sets is not None else ms.load_case_sets()
    ops = {op: {"dtype": e["dtype"], "case_set_id": e["case_set_id"], "kinds": derive(op, e)}
           for op, e in sorted(case_sets["operators"].items())}
    return {"schema": SCHEMA, "source": "tilebench.data.tensors generators on every frozen case (case_sets.yaml)",
            "operators": ops}


_CACHE: dict = {}


def load_manifest() -> dict:
    path = ms.MANIFEST_DIR / MANIFEST_NAME
    text = path.read_text()
    key = ms.sha256_text(text)
    if key in _CACHE:
        return _CACHE[key]
    data = ms.load_yaml(MANIFEST_NAME)
    if data.get("schema") != SCHEMA:
        raise ms.ManifestError(f"{MANIFEST_NAME}: schema must be {SCHEMA}")
    case_sets = ms.load_case_sets()["operators"]
    ops = data.get("operators") or {}
    if set(ops) != set(case_sets):
        raise ms.ManifestError(f"{MANIFEST_NAME}: operators differ from case_sets.yaml")
    for op, e in ops.items():
        if (e.get("dtype"), e.get("case_set_id")) != (case_sets[op]["dtype"], case_sets[op]["case_set_id"]):
            raise ms.ManifestError(f"{MANIFEST_NAME}: {op} was derived for another case set")
        if not e.get("kinds") or any(k not in KINDS for k in e["kinds"]):
            raise ms.ManifestError(f"{MANIFEST_NAME}: {op} kinds must be a non-empty list of {KINDS}")
    _CACHE[key] = data
    return data


def scalar_positions(operator: str) -> frozenset:
    """Positions of `run()` inputs that are Python numbers for this operator's task."""
    kinds = (load_manifest()["operators"].get(operator) or {}).get("kinds") or []
    return frozenset(i for i, k in enumerate(kinds) if k == "scalar")


if __name__ == "__main__":
    import yaml
    body = build_manifest()
    header = ("# Kinds of the positional inputs every task passes to run() (checker v4), derived from the input\n"
              "# generators on every frozen case. Generated by `python -m tilebench.llm.v2.tasks.input_kinds`; do not edit.\n")
    (ms.MANIFEST_DIR / MANIFEST_NAME).write_text(header + yaml.safe_dump(body, sort_keys=True, default_flow_style=None, width=120))
    print({op: e["kinds"] for op, e in body["operators"].items()})
