"""One representative dtype per operator (protocol revision 3).

Study-owner decision of 2026-10-06: a formal task is (operator, ONE selected
dtype), identical for every DSL, model, condition and device. The selection
is predeclared, deterministic and never uses performance information
(latency, SOL, human kernel performance or LLM success rate). Rules, applied
in this order:

  C  the operator is int8-specific (quantized-int8 task)        -> int8
  B  the operator's semantics are integer (histogram/radix keys) -> the natural integer dtype
     the contract/reference requires
  D  exactly one eligible dtype                                  -> that dtype
  A  general floating-point operator                             -> fp16, else bf16, else fp32,
                                                                    else the remaining floating dtype

Indexing/sorting/selection operators whose eligible dtypes are all floating
(argmax, bitonic_sort, top_k_selection, destindex payload, ...) keep their
integer part (indices) at its fixed dtype; the task dtype is the payload
dtype and rule A applies. The representative case of the selected dtype is
the unchanged largest-case rule (tasks.case_selection).

`representative_dtypes.yaml` is generated by `build_manifest()` and checked
by `validate_manifest()` against the operator configs on every load: an
entry whose dtype differs from the rule's result, or whose eligible list
differs from the config, is an error."""
from __future__ import annotations

from tilebench.llm.v2.manifests import schema as ms
from tilebench.llm.v2.tasks.case_selection import load_operator_config, operator_dtypes, select_representative_case

MANIFEST_NAME = "representative_dtypes.yaml"
SCHEMA = "tilebench-llm-representative-dtypes/1"

# Semantic classes, declared from the operators' definitions (contract + functional reference), not from results.
INT8_SPECIFIC = {
    "dequantize_rowwise": "dequantizes an int8 tensor with per-row scales: the task is defined on int8 input",
    "matmul_int8": "int8 activations times packed low-bit int8 weights with int32 output: the task is defined on int8 operands",
}
INTEGER_SEMANTICS = {
    "histogramming": ("int32", "counts integer bin indices; the reference takes int32 input"),
    "radix_sort": ("int32", "sorts integer keys by radix digits; the task's keys are int32 (config.yaml)"),
}
FLOAT_PRIORITY = ("fp16", "bf16", "fp32")
FLOATING = ("fp16", "bf16", "fp32", "fp64", "fp8_e4m3fn", "fp8_e5m2")
RULE_TEXT = {
    "A": "general floating-point operator: fp16 if eligible, else bf16, else fp32, else the remaining floating dtype",
    "B": "integer-semantics operator: the natural integer dtype required by the contract/reference",
    "C": "int8-specific / quantized-int8 operator: int8",
    "D": "exactly one eligible dtype: that dtype",
}


def select_dtype(operator: str, eligible: list[str]) -> tuple[str, str, str]:
    """(dtype, rule letter, reason) for one operator."""
    if not eligible:
        raise ValueError(f"{operator}: no eligible dtype")
    if operator in INT8_SPECIFIC:
        if "int8" not in eligible:
            raise ValueError(f"{operator}: declared int8-specific but int8 is not eligible ({eligible})")
        return "int8", "C", INT8_SPECIFIC[operator]
    if operator in INTEGER_SEMANTICS:
        dt, why = INTEGER_SEMANTICS[operator]
        if dt not in eligible:
            raise ValueError(f"{operator}: natural integer dtype {dt} is not eligible ({eligible})")
        return dt, "B", why
    if len(eligible) == 1:
        return eligible[0], "D", f"only eligible dtype is {eligible[0]}"
    for dt in FLOAT_PRIORITY:
        if dt in eligible:
            skipped = [d for d in FLOAT_PRIORITY if d in eligible and FLOAT_PRIORITY.index(d) < FLOAT_PRIORITY.index(dt)]
            return dt, "A", f"general operator; first eligible in the priority fp16 > bf16 > fp32 is {dt}" + \
                (f" (skipped {skipped})" if skipped else "")
    rest = sorted(d for d in eligible if d in FLOATING)
    if len(rest) == 1:
        return rest[0], "A", f"general operator; the only floating dtype is {rest[0]}"
    raise ValueError(f"{operator}: no rule selects a dtype from {eligible}")


def build_manifest(operators: list[str] | None = None, folds: dict | None = None) -> dict:
    from tilebench.paths import list_operators
    folds = folds or ms.load_folds()
    entries = {}
    for op in operators or list_operators():
        cfg = load_operator_config(op)
        cfg["_operator"] = op
        eligible = operator_dtypes(cfg)
        dt, rule, why = select_dtype(op, eligible)
        sel = select_representative_case(op, dt, cfg)
        entries[op] = {"dtype": dt, "rule": rule, "reason": why, "eligible_dtypes": eligible,
                       "fold": ms.fold_of(folds, op),
                       "case": {"case_id": sel.case_id, "case_index": sel.case_index, "params": sel.params,
                                "problem_size": sel.problem_size}}
    return {"schema": SCHEMA, "rules": RULE_TEXT,
            "rule_order": ["C", "B", "D", "A"],
            "case_rule": "largest infer_problem_size() among the selected dtype's expanded cases; ties keep the last case",
            "inputs_excluded": ["latency", "SOL/T_emp", "human kernel performance", "LLM success rate"],
            "cross_device": ("transfer devices use the same selected dtype; an operator whose selected dtype a target "
                             "device does not support is excluded from paired cross-device coverage, never re-typed"),
            "operators": entries}


def load_manifest() -> dict:
    data = ms.load_yaml(MANIFEST_NAME)
    validate_manifest(data)
    return data


def validate_manifest(data: dict, operators: list[str] | None = None) -> None:
    from tilebench.paths import list_operators
    if data.get("schema") != SCHEMA:
        raise ms.ManifestError(f"{MANIFEST_NAME}: schema must be {SCHEMA}")
    if data.get("status") != "frozen" or not data.get("approved_by"):
        raise ms.ManifestError(f"{MANIFEST_NAME}: must be frozen with approved_by")
    ops = operators or list_operators()
    entries = data.get("operators") or {}
    if sorted(entries) != sorted(ops):
        raise ms.ManifestError(f"{MANIFEST_NAME}: operators {sorted(set(ops) ^ set(entries))} missing or unknown")
    expected = build_manifest(ops)["operators"]
    for op in ops:
        got, exp = entries[op], expected[op]
        for k in ("dtype", "rule", "eligible_dtypes", "fold"):
            if got.get(k) != exp[k]:
                raise ms.ManifestError(f"{MANIFEST_NAME}: {op}.{k} = {got.get(k)!r}, the predeclared rule gives {exp[k]!r}")
        if (got.get("case") or {}).get("case_id") != exp["case"]["case_id"]:
            raise ms.ManifestError(f"{MANIFEST_NAME}: {op} case differs from the largest-case rule")


def selected(data: dict | None = None) -> dict[str, str]:
    """operator -> selected dtype."""
    data = data if data is not None else load_manifest()
    return {op: e["dtype"] for op, e in data["operators"].items()}
