test_cases:
  - M: 1024
    K_b: 256
    N: 1024
    block_size: 128

  - M: 4096
    K_b: 1024
    N: 4096
    block_size: 128

  - M: 8192
    K_b: 2048
    N: 8192
    block_size: 128

  - M: 2048
    K_b: 1024
    N: 8192
    block_size: 128