test_cases:
  - batch_size: 8
    seq_len: 1024
    kv_nope_head_num: 12
    kv_rope_head_num: 1
    kv_nope_head_dim: 128
    kv_rope_head_dim: 64
    dtype: "float16"
  - batch_size: 4
    seq_len: 2048
    kv_nope_head_num: 12
    kv_rope_head_num: 1
    kv_nope_head_dim: 128
    kv_rope_head_dim: 64
    dtype: "float16"
  - batch_size: 2
    seq_len: 1024
    kv_nope_head_num: 16
    kv_rope_head_num: 2
    kv_nope_head_dim: 64
    kv_rope_head_dim: 64
    dtype: "float32"
