test_cases:

  - M: 2048
    K: 2048
    N: 2048
    dtype: "float32"
    block_size: 128
    grid_programs: 108

  - M: 2176
    K: 2176
    N: 2176
    dtype: "float32"
    block_size: 128
    grid_programs: 108

  - M: 256
    K: 8192
    N: 4096
    dtype: "float32"
    block_size: 128
    grid_programs: 108

  - M: 4096
    K: 8192
    N: 5120
    dtype: "float32"
    block_size: 128
    grid_programs: 108