test_cases:
  - n: 1048576  # 2^20
    dtype: "float32"
    block_size: 1024
  - n: 4194304  # 2^22
    dtype: "float32"
    block_size: 512
  - n: 16777216 # 2^24
    dtype: "float32"
    block_size: 256
  - n: 1048576
    dtype: "float16"
    block_size: 1024
